name: Prod Build & Deploy

on:
  release:
    types: [created]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "hello when triggered release is created  "
